-- ----------------------------
-- Records of departments
-- ----------------------------
INSERT INTO "public"."departments" VALUES (5, 'ANTIOQUIA');
INSERT INTO "public"."departments" VALUES (8, 'ATLÁNTICO');
INSERT INTO "public"."departments" VALUES (11, 'BOGOTÁ, D.C.');
INSERT INTO "public"."departments" VALUES (13, 'BOLÍVAR');
INSERT INTO "public"."departments" VALUES (15, 'BOYACÁ');
INSERT INTO "public"."departments" VALUES (17, 'CALDAS');
INSERT INTO "public"."departments" VALUES (18, 'CAQUETÁ');
INSERT INTO "public"."departments" VALUES (19, 'CAUCA');
INSERT INTO "public"."departments" VALUES (20, 'CESAR');
INSERT INTO "public"."departments" VALUES (23, 'CÓRDOBA');
INSERT INTO "public"."departments" VALUES (25, 'CUNDINAMARCA');
INSERT INTO "public"."departments" VALUES (27, 'CHOCÓ');
INSERT INTO "public"."departments" VALUES (41, 'HUILA');
INSERT INTO "public"."departments" VALUES (44, 'LA GUAJIRA');
INSERT INTO "public"."departments" VALUES (47, 'MAGDALENA');
INSERT INTO "public"."departments" VALUES (50, 'META');
INSERT INTO "public"."departments" VALUES (52, 'NARIÑO');
INSERT INTO "public"."departments" VALUES (54, 'NORTE DE SANTANDER');
INSERT INTO "public"."departments" VALUES (63, 'QUINDIO');
INSERT INTO "public"."departments" VALUES (66, 'RISARALDA');
INSERT INTO "public"."departments" VALUES (68, 'SANTANDER');
INSERT INTO "public"."departments" VALUES (70, 'SUCRE');
INSERT INTO "public"."departments" VALUES (73, 'TOLIMA');
INSERT INTO "public"."departments" VALUES (76, 'VALLE DEL CAUCA');
INSERT INTO "public"."departments" VALUES (81, 'ARAUCA');
INSERT INTO "public"."departments" VALUES (85, 'CASANARE');
INSERT INTO "public"."departments" VALUES (86, 'PUTUMAYO');
INSERT INTO "public"."departments" VALUES (88, 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA');
INSERT INTO "public"."departments" VALUES (91, 'AMAZONAS');
INSERT INTO "public"."departments" VALUES (94, 'GUAINÍA');
INSERT INTO "public"."departments" VALUES (95, 'GUAVIARE');
INSERT INTO "public"."departments" VALUES (97, 'VAUPÉS');
INSERT INTO "public"."departments" VALUES (99, 'VICHADA');

-- ----------------------------
-- Records of cities
-- ----------------------------
INSERT INTO "public"."cities" VALUES (1, 'Abriaquí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (2, 'Acacías', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (3, 'Acandí', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (4, 'Acevedo', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (5, 'Achí', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (6, 'Agrado', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (7, 'Agua de Dios', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (8, 'Aguachica', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (9, 'Aguada', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (10, 'Aguadas', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (11, 'Aguazul', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (12, 'Agustín Codazzi', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (13, 'Aipe', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (14, 'Albania', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (15, 'Albania', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (16, 'Albania', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (17, 'Albán', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (18, 'Albán (San José)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (19, 'Alcalá', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (20, 'Alejandria', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (21, 'Algarrobo', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (22, 'Algeciras', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (23, 'Almaguer', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (24, 'Almeida', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (25, 'Alpujarra', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (26, 'Altamira', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (27, 'Alto Baudó (Pie de Pato)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (28, 'Altos del Rosario', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (29, 'Alvarado', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (30, 'Amagá', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (31, 'Amalfi', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (32, 'Ambalema', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (33, 'Anapoima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (34, 'Ancuya', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (35, 'Andalucía', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (36, 'Andes', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (37, 'Angelópolis', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (38, 'Angostura', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (39, 'Anolaima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (40, 'Anorí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (41, 'Anserma', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (42, 'Ansermanuevo', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (43, 'Anzoátegui', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (44, 'Anzá', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (45, 'Apartadó', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (46, 'Apulo', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (47, 'Apía', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (48, 'Aquitania', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (49, 'Aracataca', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (50, 'Aranzazu', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (51, 'Aratoca', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (52, 'Arauca', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (53, 'Arauquita', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (54, 'Arbeláez', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (55, 'Arboleda (Berruecos)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (56, 'Arboledas', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (57, 'Arboletes', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (58, 'Arcabuco', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (59, 'Arenal', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (60, 'Argelia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (61, 'Argelia', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (62, 'Argelia', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (63, 'Ariguaní (El Difícil)', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (64, 'Arjona', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (65, 'Armenia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (66, 'Armenia', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (67, 'Armero (Guayabal)', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (68, 'Arroyohondo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (69, 'Astrea', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (70, 'Ataco', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (71, 'Atrato (Yuto)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (72, 'Ayapel', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (73, 'Bagadó', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (74, 'Bahía Solano (Mútis)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (75, 'Bajo Baudó (Pizarro)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (76, 'Balboa', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (77, 'Balboa', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (78, 'Baranoa', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (79, 'Baraya', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (80, 'Barbacoas', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (81, 'Barbosa', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (82, 'Barbosa', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (83, 'Barichara', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (84, 'Barranca de Upía', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (85, 'Barrancabermeja', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (86, 'Barrancas', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (87, 'Barranco de Loba', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (88, 'Barranquilla', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (89, 'Becerríl', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (90, 'Belalcázar', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (91, 'Bello', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (92, 'Belmira', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (93, 'Beltrán', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (94, 'Belén', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (95, 'Belén', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (96, 'Belén de Bajirá', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (97, 'Belén de Umbría', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (98, 'Belén de los Andaquíes', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (99, 'Berbeo', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (100, 'Betania', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (101, 'Beteitiva', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (102, 'Betulia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (103, 'Betulia', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (104, 'Bituima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (105, 'Boavita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (106, 'Bochalema', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (107, 'Bogotá D.C.', 11, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (108, 'Bojacá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (109, 'Bojayá (Bellavista)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (110, 'Bolívar', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (111, 'Bolívar', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (112, 'Bolívar', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (113, 'Bolívar', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (114, 'Bosconia', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (115, 'Boyacá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (116, 'Briceño', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (117, 'Briceño', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (118, 'Bucaramanga', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (119, 'Bucarasica', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (120, 'Buenaventura', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (121, 'Buenavista', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (122, 'Buenavista', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (123, 'Buenavista', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (124, 'Buenavista', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (125, 'Buenos Aires', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (126, 'Buesaco', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (127, 'Buga', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (128, 'Bugalagrande', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (129, 'Burítica', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (130, 'Busbanza', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (131, 'Cabrera', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (132, 'Cabrera', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (133, 'Cabuyaro', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (134, 'Cachipay', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (135, 'Caicedo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (136, 'Caicedonia', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (137, 'Caimito', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (138, 'Cajamarca', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (139, 'Cajibío', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (140, 'Cajicá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (141, 'Calamar', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (142, 'Calamar', 95, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (143, 'Calarcá', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (144, 'Caldas', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (145, 'Caldas', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (146, 'Caldono', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (147, 'California', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (148, 'Calima (Darién)', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (149, 'Caloto', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (150, 'Calí', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (151, 'Campamento', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (152, 'Campo de la Cruz', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (153, 'Campoalegre', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (154, 'Campohermoso', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (155, 'Canalete', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (156, 'Candelaria', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (157, 'Candelaria', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (158, 'Cantagallo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (159, 'Cantón de San Pablo', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (160, 'Caparrapí', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (161, 'Capitanejo', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (162, 'Caracolí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (163, 'Caramanta', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (164, 'Carcasí', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (165, 'Carepa', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (166, 'Carmen de Apicalá', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (167, 'Carmen de Carupa', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (168, 'Carmen de Viboral', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (169, 'Carmen del Darién (CURBARADÓ)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (170, 'Carolina', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (171, 'Cartagena', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (172, 'Cartagena del Chairá', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (173, 'Cartago', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (174, 'Carurú', 97, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (175, 'Casabianca', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (176, 'Castilla la Nueva', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (177, 'Caucasia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (178, 'Cañasgordas', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (179, 'Cepita', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (180, 'Cereté', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (181, 'Cerinza', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (182, 'Cerrito', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (183, 'Cerro San Antonio', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (184, 'Chachaguí', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (185, 'Chaguaní', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (186, 'Chalán', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (187, 'Chaparral', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (188, 'Charalá', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (189, 'Charta', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (190, 'Chigorodó', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (191, 'Chima', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (192, 'Chimichagua', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (193, 'Chimá', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (194, 'Chinavita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (195, 'Chinchiná', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (196, 'Chinácota', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (197, 'Chinú', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (198, 'Chipaque', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (199, 'Chipatá', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (200, 'Chiquinquirá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (201, 'Chiriguaná', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (202, 'Chiscas', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (203, 'Chita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (204, 'Chitagá', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (205, 'Chitaraque', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (206, 'Chivatá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (207, 'Chivolo', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (208, 'Choachí', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (209, 'Chocontá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (210, 'Chámeza', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (211, 'Chía', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (212, 'Chíquiza', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (213, 'Chívor', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (214, 'Cicuco', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (215, 'Cimitarra', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (216, 'Circasia', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (217, 'Cisneros', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (218, 'Ciénaga', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (219, 'Ciénaga', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (220, 'Ciénaga de Oro', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (221, 'Clemencia', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (222, 'Cocorná', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (223, 'Coello', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (224, 'Cogua', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (225, 'Colombia', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (226, 'Colosó (Ricaurte)', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (227, 'Colón', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (228, 'Colón (Génova)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (229, 'Concepción', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (230, 'Concepción', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (231, 'Concordia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (232, 'Concordia', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (233, 'Condoto', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (234, 'Confines', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (235, 'Consaca', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (236, 'Contadero', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (237, 'Contratación', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (238, 'Convención', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (239, 'Copacabana', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (240, 'Coper', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (241, 'Cordobá', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (242, 'Corinto', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (243, 'Coromoro', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (244, 'Corozal', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (245, 'Corrales', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (246, 'Cota', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (247, 'Cotorra', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (248, 'Covarachía', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (249, 'Coveñas', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (250, 'Coyaima', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (251, 'Cravo Norte', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (252, 'Cuaspud (Carlosama)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (253, 'Cubarral', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (254, 'Cubará', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (255, 'Cucaita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (256, 'Cucunubá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (257, 'Cucutilla', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (258, 'Cuitiva', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (259, 'Cumaral', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (260, 'Cumaribo', 99, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (261, 'Cumbal', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (262, 'Cumbitara', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (263, 'Cunday', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (264, 'Curillo', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (265, 'Curití', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (266, 'Curumaní', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (267, 'Cáceres', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (268, 'Cáchira', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (269, 'Cácota', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (270, 'Cáqueza', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (271, 'Cértegui', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (272, 'Cómbita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (273, 'Córdoba', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (274, 'Córdoba', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (275, 'Cúcuta', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (276, 'Dabeiba', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (277, 'Dagua', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (278, 'Dibulla', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (279, 'Distracción', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (280, 'Dolores', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (281, 'Don Matías', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (282, 'Dos Quebradas', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (283, 'Duitama', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (284, 'Durania', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (285, 'Ebéjico', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (286, 'El Bagre', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (287, 'El Banco', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (288, 'El Cairo', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (289, 'El Calvario', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (290, 'El Carmen', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (291, 'El Carmen', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (292, 'El Carmen de Atrato', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (293, 'El Carmen de Bolívar', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (294, 'El Castillo', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (295, 'El Cerrito', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (296, 'El Charco', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (297, 'El Cocuy', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (298, 'El Colegio', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (299, 'El Copey', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (300, 'El Doncello', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (301, 'El Dorado', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (302, 'El Dovio', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (303, 'El Espino', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (304, 'El Guacamayo', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (305, 'El Guamo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (306, 'El Molino', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (307, 'El Paso', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (308, 'El Paujil', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (309, 'El Peñol', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (310, 'El Peñon', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (311, 'El Peñon', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (312, 'El Peñón', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (313, 'El Piñon', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (314, 'El Playón', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (315, 'El Retorno', 95, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (316, 'El Retén', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (317, 'El Roble', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (318, 'El Rosal', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (319, 'El Rosario', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (320, 'El Tablón de Gómez', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (321, 'El Tambo', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (322, 'El Tambo', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (323, 'El Tarra', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (324, 'El Zulia', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (325, 'El Águila', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (326, 'Elías', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (327, 'Encino', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (328, 'Enciso', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (329, 'Entrerríos', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (330, 'Envigado', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (331, 'Espinal', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (332, 'Facatativá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (333, 'Falan', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (334, 'Filadelfia', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (335, 'Filandia', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (336, 'Firavitoba', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (337, 'Flandes', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (338, 'Florencia', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (339, 'Florencia', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (340, 'Floresta', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (341, 'Florida', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (342, 'Floridablanca', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (343, 'Florián', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (344, 'Fonseca', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (345, 'Fortúl', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (346, 'Fosca', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (347, 'Francisco Pizarro', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (348, 'Fredonia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (349, 'Fresno', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (350, 'Frontino', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (351, 'Fuente de Oro', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (352, 'Fundación', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (353, 'Funes', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (354, 'Funza', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (355, 'Fusagasugá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (356, 'Fómeque', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (357, 'Fúquene', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (358, 'Gachalá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (359, 'Gachancipá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (360, 'Gachantivá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (361, 'Gachetá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (362, 'Galapa', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (363, 'Galeras (Nueva Granada)', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (364, 'Galán', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (365, 'Gama', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (366, 'Gamarra', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (367, 'Garagoa', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (368, 'Garzón', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (369, 'Gigante', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (370, 'Ginebra', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (371, 'Giraldo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (372, 'Girardot', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (373, 'Girardota', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (374, 'Girón', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (375, 'Gonzalez', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (376, 'Gramalote', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (377, 'Granada', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (378, 'Granada', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (379, 'Granada', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (380, 'Guaca', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (381, 'Guacamayas', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (382, 'Guacarí', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (383, 'Guachavés', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (384, 'Guachené', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (385, 'Guachetá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (386, 'Guachucal', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (387, 'Guadalupe', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (388, 'Guadalupe', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (389, 'Guadalupe', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (390, 'Guaduas', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (391, 'Guaitarilla', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (392, 'Gualmatán', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (393, 'Guamal', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (394, 'Guamal', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (395, 'Guamo', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (396, 'Guapota', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (397, 'Guapí', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (398, 'Guaranda', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (399, 'Guarne', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (400, 'Guasca', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (401, 'Guatapé', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (402, 'Guataquí', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (403, 'Guatavita', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (404, 'Guateque', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (405, 'Guavatá', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (406, 'Guayabal de Siquima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (407, 'Guayabetal', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (408, 'Guayatá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (409, 'Guepsa', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (410, 'Guicán', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (411, 'Gutiérrez', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (412, 'Guática', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (413, 'Gámbita', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (414, 'Gámeza', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (415, 'Génova', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (416, 'Gómez Plata', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (417, 'Hacarí', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (418, 'Hatillo de Loba', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (419, 'Hato', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (420, 'Hato Corozal', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (421, 'Hatonuevo', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (422, 'Heliconia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (423, 'Herrán', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (424, 'Herveo', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (425, 'Hispania', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (426, 'Hobo', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (427, 'Honda', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (428, 'Ibagué', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (429, 'Icononzo', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (430, 'Iles', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (431, 'Imúes', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (432, 'Inzá', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (433, 'Inírida', 94, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (434, 'Ipiales', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (435, 'Isnos', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (436, 'Istmina', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (437, 'Itagüí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (438, 'Ituango', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (439, 'Izá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (440, 'Jambaló', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (441, 'Jamundí', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (442, 'Jardín', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (443, 'Jenesano', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (444, 'Jericó', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (445, 'Jericó', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (446, 'Jerusalén', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (447, 'Jesús María', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (448, 'Jordán', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (449, 'Juan de Acosta', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (450, 'Junín', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (451, 'Juradó', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (452, 'La Apartada y La Frontera', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (453, 'La Argentina', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (454, 'La Belleza', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (455, 'La Calera', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (456, 'La Capilla', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (457, 'La Ceja', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (458, 'La Celia', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (459, 'La Cruz', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (460, 'La Cumbre', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (461, 'La Dorada', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (462, 'La Esperanza', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (463, 'La Estrella', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (464, 'La Florida', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (465, 'La Gloria', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (466, 'La Jagua de Ibirico', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (467, 'La Jagua del Pilar', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (468, 'La Llanada', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (469, 'La Macarena', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (470, 'La Merced', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (471, 'La Mesa', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (472, 'La Montañita', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (473, 'La Palma', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (474, 'La Paz', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (475, 'La Paz (Robles)', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (476, 'La Peña', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (477, 'La Pintada', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (478, 'La Plata', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (479, 'La Playa', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (480, 'La Primavera', 99, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (481, 'La Salina', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (482, 'La Sierra', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (483, 'La Tebaida', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (484, 'La Tola', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (485, 'La Unión', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (486, 'La Unión', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (487, 'La Unión', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (488, 'La Unión', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (489, 'La Uvita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (490, 'La Vega', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (491, 'La Vega', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (492, 'La Victoria', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (493, 'La Victoria', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (494, 'La Victoria', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (495, 'La Virginia', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (496, 'Labateca', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (497, 'Labranzagrande', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (498, 'Landázuri', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (499, 'Lebrija', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (500, 'Leiva', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (501, 'Lejanías', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (502, 'Lenguazaque', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (503, 'Leticia', 91, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (504, 'Liborina', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (505, 'Linares', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (506, 'Lloró', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (507, 'Lorica', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (508, 'Los Córdobas', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (509, 'Los Palmitos', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (510, 'Los Patios', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (511, 'Los Santos', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (512, 'Lourdes', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (513, 'Luruaco', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (514, 'Lérida', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (515, 'Líbano', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (516, 'López (Micay)', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (517, 'Macanal', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (518, 'Macaravita', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (519, 'Maceo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (520, 'Machetá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (521, 'Madrid', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (522, 'Magangué', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (523, 'Magüi (Payán)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (524, 'Mahates', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (525, 'Maicao', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (526, 'Majagual', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (527, 'Malambo', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (528, 'Mallama (Piedrancha)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (529, 'Manatí', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (530, 'Manaure', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (531, 'Manaure Balcón del Cesar', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (532, 'Manizales', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (533, 'Manta', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (534, 'Manzanares', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (535, 'Maní', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (536, 'Mapiripan', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (537, 'Margarita', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (538, 'Marinilla', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (539, 'Maripí', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (540, 'Mariquita', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (541, 'Marmato', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (542, 'Marquetalia', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (543, 'Marsella', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (544, 'Marulanda', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (545, 'María la Baja', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (546, 'Matanza', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (547, 'Medellín', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (548, 'Medina', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (549, 'Medio Atrato', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (550, 'Medio Baudó', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (551, 'Medio San Juan (ANDAGOYA)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (552, 'Melgar', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (553, 'Mercaderes', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (554, 'Mesetas', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (555, 'Milán', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (556, 'Miraflores', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (557, 'Miraflores', 95, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (558, 'Miranda', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (559, 'Mistrató', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (560, 'Mitú', 97, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (561, 'Mocoa', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (562, 'Mogotes', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (563, 'Molagavita', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (564, 'Momil', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (565, 'Mompós', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (566, 'Mongua', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (567, 'Monguí', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (568, 'Moniquirá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (569, 'Montebello', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (570, 'Montecristo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (571, 'Montelíbano', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (572, 'Montenegro', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (573, 'Monteria', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (574, 'Monterrey', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (575, 'Morales', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (576, 'Morales', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (577, 'Morelia', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (578, 'Morroa', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (579, 'Mosquera', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (580, 'Mosquera', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (581, 'Motavita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (582, 'Moñitos', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (583, 'Murillo', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (584, 'Murindó', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (585, 'Mutatá', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (586, 'Mutiscua', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (587, 'Muzo', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (588, 'Málaga', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (589, 'Nariño', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (590, 'Nariño', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (591, 'Nariño', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (592, 'Natagaima', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (593, 'Nechí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (594, 'Necoclí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (595, 'Neira', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (596, 'Neiva', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (597, 'Nemocón', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (598, 'Nilo', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (599, 'Nimaima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (600, 'Nobsa', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (601, 'Nocaima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (602, 'Norcasia', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (603, 'Norosí', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (604, 'Novita', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (605, 'Nueva Granada', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (606, 'Nuevo Colón', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (607, 'Nunchía', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (608, 'Nuquí', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (609, 'Nátaga', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (610, 'Obando', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (611, 'Ocamonte', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (612, 'Ocaña', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (613, 'Oiba', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (614, 'Oicatá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (615, 'Olaya', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (616, 'Olaya Herrera', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (617, 'Onzaga', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (618, 'Oporapa', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (619, 'Orito', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (620, 'Orocué', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (621, 'Ortega', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (622, 'Ospina', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (623, 'Otanche', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (624, 'Ovejas', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (625, 'Pachavita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (626, 'Pacho', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (627, 'Padilla', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (628, 'Paicol', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (629, 'Pailitas', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (630, 'Paime', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (631, 'Paipa', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (632, 'Pajarito', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (633, 'Palermo', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (634, 'Palestina', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (635, 'Palestina', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (636, 'Palmar', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (637, 'Palmar de Varela', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (638, 'Palmas del Socorro', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (639, 'Palmira', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (640, 'Palmito', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (641, 'Palocabildo', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (642, 'Pamplona', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (643, 'Pamplonita', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (644, 'Pandi', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (645, 'Panqueba', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (646, 'Paratebueno', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (647, 'Pasca', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (648, 'Patía (El Bordo)', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (649, 'Pauna', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (650, 'Paya', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (651, 'Paz de Ariporo', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (652, 'Paz de Río', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (653, 'Pedraza', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (654, 'Pelaya', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (655, 'Pensilvania', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (656, 'Peque', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (657, 'Pereira', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (658, 'Pesca', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (659, 'Peñol', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (660, 'Piamonte', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (661, 'Pie de Cuesta', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (662, 'Piedras', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (663, 'Piendamó', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (664, 'Pijao', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (665, 'Pijiño', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (666, 'Pinchote', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (667, 'Pinillos', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (668, 'Piojo', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (669, 'Pisva', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (670, 'Pital', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (671, 'Pitalito', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (672, 'Pivijay', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (673, 'Planadas', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (674, 'Planeta Rica', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (675, 'Plato', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (676, 'Policarpa', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (677, 'Polonuevo', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (678, 'Ponedera', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (679, 'Popayán', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (680, 'Pore', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (681, 'Potosí', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (682, 'Pradera', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (683, 'Prado', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (684, 'Providencia', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (685, 'Providencia', 88, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (686, 'Pueblo Bello', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (687, 'Pueblo Nuevo', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (688, 'Pueblo Rico', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (689, 'Pueblorrico', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (690, 'Puebloviejo', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (691, 'Puente Nacional', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (692, 'Puerres', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (693, 'Puerto Asís', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (694, 'Puerto Berrío', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (695, 'Puerto Boyacá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (696, 'Puerto Caicedo', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (697, 'Puerto Carreño', 99, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (698, 'Puerto Colombia', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (699, 'Puerto Concordia', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (700, 'Puerto Escondido', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (701, 'Puerto Gaitán', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (702, 'Puerto Guzmán', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (703, 'Puerto Leguízamo', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (704, 'Puerto Libertador', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (705, 'Puerto Lleras', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (706, 'Puerto López', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (707, 'Puerto Nare', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (708, 'Puerto Nariño', 91, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (709, 'Puerto Parra', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (710, 'Puerto Rico', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (711, 'Puerto Rico', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (712, 'Puerto Rondón', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (713, 'Puerto Salgar', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (714, 'Puerto Santander', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (715, 'Puerto Tejada', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (716, 'Puerto Triunfo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (717, 'Puerto Wilches', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (718, 'Pulí', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (719, 'Pupiales', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (720, 'Puracé (Coconuco)', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (721, 'Purificación', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (722, 'Purísima', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (723, 'Pácora', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (724, 'Páez', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (725, 'Páez (Belalcazar)', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (726, 'Páramo', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (727, 'Quebradanegra', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (728, 'Quetame', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (729, 'Quibdó', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (730, 'Quimbaya', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (731, 'Quinchía', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (732, 'Quipama', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (733, 'Quipile', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (734, 'Ragonvalia', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (735, 'Ramiriquí', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (736, 'Recetor', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (737, 'Regidor', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (738, 'Remedios', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (739, 'Remolino', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (740, 'Repelón', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (741, 'Restrepo', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (742, 'Restrepo', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (743, 'Retiro', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (744, 'Ricaurte', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (745, 'Ricaurte', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (746, 'Rio Negro', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (747, 'Rioblanco', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (748, 'Riofrío', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (749, 'Riohacha', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (750, 'Risaralda', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (751, 'Rivera', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (752, 'Roberto Payán (San José)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (753, 'Roldanillo', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (754, 'Roncesvalles', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (755, 'Rondón', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (756, 'Rosas', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (757, 'Rovira', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (758, 'Ráquira', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (759, 'Río Iró', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (760, 'Río Quito', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (761, 'Río Sucio', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (762, 'Río Viejo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (763, 'Río de oro', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (764, 'Ríonegro', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (765, 'Ríosucio', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (766, 'Sabana de Torres', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (767, 'Sabanagrande', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (768, 'Sabanalarga', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (769, 'Sabanalarga', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (770, 'Sabanalarga', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (771, 'Sabanas de San Angel (SAN ANGEL)', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (772, 'Sabaneta', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (773, 'Saboyá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (774, 'Sahagún', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (775, 'Saladoblanco', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (776, 'Salamina', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (777, 'Salamina', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (778, 'Salazar', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (779, 'Saldaña', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (780, 'Salento', 63, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (781, 'Salgar', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (782, 'Samacá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (783, 'Samaniego', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (784, 'Samaná', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (785, 'Sampués', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (786, 'San Agustín', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (787, 'San Alberto', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (788, 'San Andrés', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (789, 'San Andrés Sotavento', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (790, 'San Andrés de Cuerquía', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (791, 'San Antero', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (792, 'San Antonio', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (793, 'San Antonio de Tequendama', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (794, 'San Benito', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (795, 'San Benito Abad', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (796, 'San Bernardo', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (797, 'San Bernardo', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (798, 'San Bernardo del Viento', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (799, 'San Calixto', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (800, 'San Carlos', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (801, 'San Carlos', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (802, 'San Carlos de Guaroa', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (803, 'San Cayetano', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (804, 'San Cayetano', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (805, 'San Cristobal', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (806, 'San Diego', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (807, 'San Eduardo', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (808, 'San Estanislao', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (809, 'San Fernando', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (810, 'San Francisco', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (811, 'San Francisco', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (812, 'San Francisco', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (813, 'San Gíl', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (814, 'San Jacinto', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (815, 'San Jacinto del Cauca', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (816, 'San Jerónimo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (817, 'San Joaquín', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (818, 'San José', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (819, 'San José de Miranda', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (820, 'San José de Montaña', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (821, 'San José de Pare', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (822, 'San José de Uré', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (823, 'San José del Fragua', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (824, 'San José del Guaviare', 95, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (825, 'San José del Palmar', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (826, 'San Juan de Arama', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (827, 'San Juan de Betulia', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (828, 'San Juan de Nepomuceno', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (829, 'San Juan de Pasto', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (830, 'San Juan de Río Seco', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (831, 'San Juan de Urabá', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (832, 'San Juan del Cesar', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (833, 'San Juanito', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (834, 'San Lorenzo', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (835, 'San Luis', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (836, 'San Luís', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (837, 'San Luís de Gaceno', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (838, 'San Luís de Palenque', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (839, 'San Marcos', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (840, 'San Martín', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (841, 'San Martín', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (842, 'San Martín de Loba', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (843, 'San Mateo', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (844, 'San Miguel', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (845, 'San Miguel', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (846, 'San Miguel de Sema', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (847, 'San Onofre', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (848, 'San Pablo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (849, 'San Pablo', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (850, 'San Pablo de Borbur', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (851, 'San Pedro', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (852, 'San Pedro', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (853, 'San Pedro', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (854, 'San Pedro de Cartago', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (855, 'San Pedro de Urabá', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (856, 'San Pelayo', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (857, 'San Rafael', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (858, 'San Roque', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (859, 'San Sebastián', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (860, 'San Sebastián de Buenavista', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (861, 'San Vicente', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (862, 'San Vicente del Caguán', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (863, 'San Vicente del Chucurí', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (864, 'San Zenón', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (865, 'Sandoná', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (866, 'Santa Ana', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (867, 'Santa Bárbara', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (868, 'Santa Bárbara', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (869, 'Santa Bárbara (Iscuandé)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (870, 'Santa Bárbara de Pinto', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (871, 'Santa Catalina', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (872, 'Santa Fé de Antioquia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (873, 'Santa Genoveva de Docorodó', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (874, 'Santa Helena del Opón', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (875, 'Santa Isabel', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (876, 'Santa Lucía', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (877, 'Santa Marta', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (878, 'Santa María', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (879, 'Santa María', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (880, 'Santa Rosa', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (881, 'Santa Rosa', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (882, 'Santa Rosa de Cabal', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (883, 'Santa Rosa de Osos', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (884, 'Santa Rosa de Viterbo', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (885, 'Santa Rosa del Sur', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (886, 'Santa Rosalía', 99, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (887, 'Santa Sofía', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (888, 'Santana', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (889, 'Santander de Quilichao', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (890, 'Santiago', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (891, 'Santiago', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (892, 'Santo Domingo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (893, 'Santo Tomás', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (894, 'Santuario', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (895, 'Santuario', 66, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (896, 'Sapuyes', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (897, 'Saravena', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (898, 'Sardinata', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (899, 'Sasaima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (900, 'Sativanorte', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (901, 'Sativasur', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (902, 'Segovia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (903, 'Sesquilé', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (904, 'Sevilla', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (905, 'Siachoque', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (906, 'Sibaté', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (907, 'Sibundoy', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (908, 'Silos', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (909, 'Silvania', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (910, 'Silvia', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (911, 'Simacota', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (912, 'Simijaca', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (913, 'Simití', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (914, 'Sincelejo', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (915, 'Sincé', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (916, 'Sipí', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (917, 'Sitionuevo', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (918, 'Soacha', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (919, 'Soatá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (920, 'Socha', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (921, 'Socorro', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (922, 'Socotá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (923, 'Sogamoso', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (924, 'Solano', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (925, 'Soledad', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (926, 'Solita', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (927, 'Somondoco', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (928, 'Sonsón', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (929, 'Sopetrán', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (930, 'Soplaviento', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (931, 'Sopó', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (932, 'Sora', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (933, 'Soracá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (934, 'Sotaquirá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (935, 'Sotara (Paispamba)', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (936, 'Sotomayor (Los Andes)', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (937, 'Suaita', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (938, 'Suan', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (939, 'Suaza', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (940, 'Subachoque', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (941, 'Sucre', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (942, 'Sucre', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (943, 'Sucre', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (944, 'Suesca', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (945, 'Supatá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (946, 'Supía', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (947, 'Suratá', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (948, 'Susa', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (949, 'Susacón', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (950, 'Sutamarchán', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (951, 'Sutatausa', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (952, 'Sutatenza', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (953, 'Suárez', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (954, 'Suárez', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (955, 'Sácama', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (956, 'Sáchica', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (957, 'Tabio', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (958, 'Tadó', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (959, 'Talaigua Nuevo', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (960, 'Tamalameque', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (961, 'Tame', 81, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (962, 'Taminango', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (963, 'Tangua', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (964, 'Taraira', 97, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (965, 'Tarazá', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (966, 'Tarqui', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (967, 'Tarso', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (968, 'Tasco', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (969, 'Tauramena', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (970, 'Tausa', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (971, 'Tello', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (972, 'Tena', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (973, 'Tenerife', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (974, 'Tenjo', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (975, 'Tenza', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (976, 'Teorama', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (977, 'Teruel', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (978, 'Tesalia', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (979, 'Tibacuy', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (980, 'Tibaná', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (981, 'Tibasosa', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (982, 'Tibirita', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (983, 'Tibú', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (984, 'Tierralta', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (985, 'Timaná', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (986, 'Timbiquí', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (987, 'Timbío', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (988, 'Tinjacá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (989, 'Tipacoque', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (990, 'Tiquisio (Puerto Rico)', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (991, 'Titiribí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (992, 'Toca', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (993, 'Tocaima', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (994, 'Tocancipá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (995, 'Toguí', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (996, 'Toledo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (997, 'Toledo', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (998, 'Tolú', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (999, 'Tolú Viejo', 70, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1000, 'Tona', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1001, 'Topagá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1002, 'Topaipí', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1003, 'Toribío', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1004, 'Toro', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1005, 'Tota', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1006, 'Totoró', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1007, 'Trinidad', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1008, 'Trujillo', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1009, 'Tubará', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1010, 'Tuchín', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1011, 'Tulúa', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1012, 'Tumaco', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1013, 'Tunja', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1014, 'Tunungua', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1015, 'Turbaco', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1016, 'Turbaná', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1017, 'Turbo', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1018, 'Turmequé', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1019, 'Tuta', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1020, 'Tutasá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1021, 'Támara', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1022, 'Támesis', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1023, 'Túquerres', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1024, 'Ubalá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1025, 'Ubaque', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1026, 'Ubaté', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1027, 'Ulloa', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1028, 'Une', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1029, 'Unguía', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1030, 'Unión Panamericana (ÁNIMAS)', 27, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1031, 'Uramita', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1032, 'Uribe', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1033, 'Uribia', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1034, 'Urrao', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1035, 'Urumita', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1036, 'Usiacuri', 8, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1037, 'Valdivia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1038, 'Valencia', 23, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1039, 'Valle de San José', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1040, 'Valle de San Juan', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1041, 'Valle del Guamuez', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1042, 'Valledupar', 20, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1043, 'Valparaiso', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1044, 'Valparaiso', 18, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1045, 'Vegachí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1046, 'Venadillo', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1047, 'Venecia', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1048, 'Venecia (Ospina Pérez)', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1049, 'Ventaquemada', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1050, 'Vergara', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1051, 'Versalles', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1052, 'Vetas', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1053, 'Viani', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1054, 'Vigía del Fuerte', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1055, 'Vijes', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1056, 'Villa Caro', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1057, 'Villa Rica', 19, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1058, 'Villa de Leiva', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1059, 'Villa del Rosario', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1060, 'Villagarzón', 86, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1061, 'Villagómez', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1062, 'Villahermosa', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1063, 'Villamaría', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1064, 'Villanueva', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1065, 'Villanueva', 44, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1066, 'Villanueva', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1067, 'Villanueva', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1068, 'Villapinzón', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1069, 'Villarrica', 73, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1070, 'Villavicencio', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1071, 'Villavieja', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1072, 'Villeta', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1073, 'Viotá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1074, 'Viracachá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1075, 'Vista Hermosa', 50, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1076, 'Viterbo', 17, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1077, 'Vélez', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1078, 'Yacopí', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1079, 'Yacuanquer', 52, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1080, 'Yaguará', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1081, 'Yalí', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1082, 'Yarumal', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1083, 'Yolombó', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1084, 'Yondó (Casabe)', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1085, 'Yopal', 85, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1086, 'Yotoco', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1087, 'Yumbo', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1088, 'Zambrano', 13, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1089, 'Zapatoca', 68, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1090, 'Zapayán (PUNTA DE PIEDRAS)', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1091, 'Zaragoza', 5, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1092, 'Zarzal', 76, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1093, 'Zetaquirá', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1094, 'Zipacón', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1095, 'Zipaquirá', 25, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1096, 'Zona Bananera (PRADO - SEVILLA)', 47, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1097, 'Ábrego', 54, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1098, 'Íquira', 41, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1099, 'Úmbita', 15, NULL, NULL, NULL);
INSERT INTO "public"."cities" VALUES (1100, 'Útica', 25, NULL, NULL, NULL);