-- ----------------------------
-- Records of touristic_places
-- ----------------------------
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 105, 'Cristo Rey', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque quis tortor tristique venenatis. Donec pellentesque lacus tortor. Nam volutpat elit vitae volutpat malesuada. Duis mollis risus massa, in efficitur augue tincidunt sed. In aliquam arcu erat, a varius nulla tempus nec. Ut non justo at magna euismod dignissim id et sapien. Sed in tincidunt sapien. Sed eu venenatis ligula. Curabitur molestie tellus ut libero sagittis, eu convallis risus facilisis. Sed diam est, dignissim at enim placerat, dignissim pulvinar elit. Aenean eget diam in mauris varius tincidunt.
Phasellus velit odio, ultrices iaculis posuere eget, scelerisque vitae erat. Ut sed suscipit sapien. Etiam id augue sit amet neque viverra congue. Aenean ullamcorper elementum mi, non suscipit velit rutrum eget. Suspendisse at euismod quam. Praesent nec molestie eros. Ut at accumsan libero, at volutpat metus. Sed commodo varius ultrices. Quisque vitae nisi non nunc dignissim faucibus. Proin euismod nec nisi vitae tristique. Donec sit amet bibendum est, quis molestie nunc. Donec felis arcu, ultricies non maximus ullamcorper, venenatis ac diam. Aenean vitae justo nec mi porta tempus lacinia ut ante. Phasellus ultrices elementum nisi, nec rhoncus dui aliquam elementum.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cristo_rey_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cristo_rey_4.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cristo_rey_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 88, 'Parque Cultural del Caribe', 'Phasellus finibus diam erat, ut dapibus nisl consectetur non. Quisque nisl diam, mollis id scelerisque ut, vestibulum vitae arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus gravida, sollicitudin nulla nec, fringilla urna. Proin aliquet ante et augue blandit, vel facilisis ligula sodales. Nullam vestibulum felis non nunc elementum molestie. Nulla sed sem quis urna hendrerit volutpat. Nulla a leo sit amet urna dictum venenatis suscipit vel ipsum. Vestibulum tempus feugiat iaculis. Maecenas ac congue leo.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt leo ac justo congue tempor. Aenean convallis diam volutpat, varius nunc ac, tincidunt enim. Vestibulum fermentum, lacus eu condimentum vestibulum, nulla metus porta turpis, non tempus lorem neque rhoncus nisi. Ut sed massa congue, porttitor elit non, imperdiet erat. Duis tincidunt congue lorem, vitae hendrerit velit volutpat et. Praesent mollis fringilla ex, et hendrerit ipsum luctus et. Cras semper felis a velit vulputate, ut bibendum lectus pulvinar. Morbi nec nibh ut ipsum porttitor sagittis. In ut rutrum ex. Duis accumsan auctor ligula at egestas. Vivamus sit amet risus ac eros ultrices rhoncus at sed est. Suspendisse eu nisl faucibus, rhoncus neque eu, pharetra enim. Aliquam erat volutpat. Quisque tempor luctus sapien vel viverra. Nulla quis nunc at ante venenatis dignissim eget tempus metus.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_cultural_del_caribe_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_cultural_del_caribe_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_cultural_del_caribe_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 118, 'San juan de girón', 'Phasellus velit odio, ultrices iaculis posuere eget, scelerisque vitae erat. Ut sed suscipit sapien. Etiam id augue sit amet neque viverra congue. Aenean ullamcorper elementum mi, non suscipit velit rutrum eget. Suspendisse at euismod quam. Praesent nec molestie eros. Ut at accumsan libero, at volutpat metus. Sed commodo varius ultrices. Quisque vitae nisi non nunc dignissim faucibus. Proin euismod nec nisi vitae tristique. Donec sit amet bibendum est, quis molestie nunc. Donec felis arcu, ultricies non maximus ullamcorper, venenatis ac diam. Aenean vitae justo nec mi porta tempus lacinia ut ante. Phasellus ultrices elementum nisi, nec rhoncus dui aliquam elementum.
Phasellus finibus diam erat, ut dapibus nisl consectetur non. Quisque nisl diam, mollis id scelerisque ut, vestibulum vitae arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus gravida, sollicitudin nulla nec, fringilla urna. Proin aliquet ante et augue blandit, vel facilisis ligula sodales. Nullam vestibulum felis non nunc elementum molestie. Nulla sed sem quis urna hendrerit volutpat. Nulla a leo sit amet urna dictum venenatis suscipit vel ipsum. Vestibulum tempus feugiat iaculis. Maecenas ac congue leo.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_juan_de_giron_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_juan_de_giron_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_juan_de_giron_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 88, 'Paseo Bolívar', 'Quisque aliquam urna ex, nec sagittis risus convallis id. Phasellus sit amet nisi luctus, elementum ligula vel, pulvinar tortor. Pellentesque eu purus non metus porttitor egestas. Sed feugiat, libero aliquam vehicula mattis, nisl quam placerat arcu, sit amet dignissim est dolor in mi. Cras venenatis sodales lectus quis gravida. Morbi sed ipsum sit amet diam sodales pellentesque. Aliquam pharetra enim sed elementum dapibus. Proin non dignissim diam. Donec consectetur lacinia libero, a porttitor leo mattis non. In sed dictum velit. Cras fermentum vehicula libero, viverra bibendum quam faucibus eget.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque quis tortor tristique venenatis. Donec pellentesque lacus tortor. Nam volutpat elit vitae volutpat malesuada. Duis mollis risus massa, in efficitur augue tincidunt sed. In aliquam arcu erat, a varius nulla tempus nec. Ut non justo at magna euismod dignissim id et sapien. Sed in tincidunt sapien. Sed eu venenatis ligula. Curabitur molestie tellus ut libero sagittis, eu convallis risus facilisis. Sed diam est, dignissim at enim placerat, dignissim pulvinar elit. Aenean eget diam in mauris varius tincidunt.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/paseo_bolivar_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/paseo_bolivar_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/paseo_bolivar_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 107, 'Plaza Bolivar', 'Quisque aliquam urna ex, nec sagittis risus convallis id. Phasellus sit amet nisi luctus, elementum ligula vel, pulvinar tortor. Pellentesque eu purus non metus porttitor egestas. Sed feugiat, libero aliquam vehicula mattis, nisl quam placerat arcu, sit amet dignissim est dolor in mi. Cras venenatis sodales lectus quis gravida. Morbi sed ipsum sit amet diam sodales pellentesque. Aliquam pharetra enim sed elementum dapibus. Proin non dignissim diam. Donec consectetur lacinia libero, a porttitor leo mattis non. In sed dictum velit. Cras fermentum vehicula libero, viverra bibendum quam faucibus eget.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque quis tortor tristique venenatis. Donec pellentesque lacus tortor. Nam volutpat elit vitae volutpat malesuada. Duis mollis risus massa, in efficitur augue tincidunt sed. In aliquam arcu erat, a varius nulla tempus nec. Ut non justo at magna euismod dignissim id et sapien. Sed in tincidunt sapien. Sed eu venenatis ligula. Curabitur molestie tellus ut libero sagittis, eu convallis risus facilisis. Sed diam est, dignissim at enim placerat, dignissim pulvinar elit. Aenean eget diam in mauris varius tincidunt.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_bolivar_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_bolivar_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_bolivar_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 401, 'Museo Histórico Comunitario', 'Phasellus finibus diam erat, ut dapibus nisl consectetur non. Quisque nisl diam, mollis id scelerisque ut, vestibulum vitae arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus gravida, sollicitudin nulla nec, fringilla urna. Proin aliquet ante et augue blandit, vel facilisis ligula sodales. Nullam vestibulum felis non nunc elementum molestie. Nulla sed sem quis urna hendrerit volutpat. Nulla a leo sit amet urna dictum venenatis suscipit vel ipsum. Vestibulum tempus feugiat iaculis. Maecenas ac congue leo.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt leo ac justo congue tempor. Aenean convallis diam volutpat, varius nunc ac, tincidunt enim. Vestibulum fermentum, lacus eu condimentum vestibulum, nulla metus porta turpis, non tempus lorem neque rhoncus nisi. Ut sed massa congue, porttitor elit non, imperdiet erat. Duis tincidunt congue lorem, vitae hendrerit velit volutpat et. Praesent mollis fringilla ex, et hendrerit ipsum luctus et. Cras semper felis a velit vulputate, ut bibendum lectus pulvinar. Morbi nec nibh ut ipsum porttitor sagittis. In ut rutrum ex. Duis accumsan auctor ligula at egestas. Vivamus sit amet risus ac eros ultrices rhoncus at sed est. Suspendisse eu nisl faucibus, rhoncus neque eu, pharetra enim. Aliquam erat volutpat. Quisque tempor luctus sapien vel viverra. Nulla quis nunc at ante venenatis dignissim eget tempus metus.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_historico_comunitario_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_historico_comunitario_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 107, 'Chorro de Quevedo', 'Phasellus finibus diam erat, ut dapibus nisl consectetur non. Quisque nisl diam, mollis id scelerisque ut, vestibulum vitae arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus gravida, sollicitudin nulla nec, fringilla urna. Proin aliquet ante et augue blandit, vel facilisis ligula sodales. Nullam vestibulum felis non nunc elementum molestie. Nulla sed sem quis urna hendrerit volutpat. Nulla a leo sit amet urna dictum venenatis suscipit vel ipsum. Vestibulum tempus feugiat iaculis. Maecenas ac congue leo.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt leo ac justo congue tempor. Aenean convallis diam volutpat, varius nunc ac, tincidunt enim. Vestibulum fermentum, lacus eu condimentum vestibulum, nulla metus porta turpis, non tempus lorem neque rhoncus nisi. Ut sed massa congue, porttitor elit non, imperdiet erat. Duis tincidunt congue lorem, vitae hendrerit velit volutpat et. Praesent mollis fringilla ex, et hendrerit ipsum luctus et. Cras semper felis a velit vulputate, ut bibendum lectus pulvinar. Morbi nec nibh ut ipsum porttitor sagittis. In ut rutrum ex. Duis accumsan auctor ligula at egestas. Vivamus sit amet risus ac eros ultrices rhoncus at sed est. Suspendisse eu nisl faucibus, rhoncus neque eu, pharetra enim. Aliquam erat volutpat. Quisque tempor luctus sapien vel viverra. Nulla quis nunc at ante venenatis dignissim eget tempus metus.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/chorro_quevedo_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/chorro_quevedo_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 118, 'Ecoparque  Cerro del Santísimo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt leo ac justo congue tempor. Aenean convallis diam volutpat, varius nunc ac, tincidunt enim. Vestibulum fermentum, lacus eu condimentum vestibulum, nulla metus porta turpis, non tempus lorem neque rhoncus nisi. Ut sed massa congue, porttitor elit non, imperdiet erat. Duis tincidunt congue lorem, vitae hendrerit velit volutpat et. Praesent mollis fringilla ex, et hendrerit ipsum luctus et. Cras semper felis a velit vulputate, ut bibendum lectus pulvinar. Morbi nec nibh ut ipsum porttitor sagittis. In ut rutrum ex. Duis accumsan auctor ligula at egestas. Vivamus sit amet risus ac eros ultrices rhoncus at sed est. Suspendisse eu nisl faucibus, rhoncus neque eu, pharetra enim. Aliquam erat volutpat. Quisque tempor luctus sapien vel viverra. Nulla quis nunc at ante venenatis dignissim eget tempus metus.
Quisque aliquam urna ex, nec sagittis risus convallis id. Phasellus sit amet nisi luctus, elementum ligula vel, pulvinar tortor. Pellentesque eu purus non metus porttitor egestas. Sed feugiat, libero aliquam vehicula mattis, nisl quam placerat arcu, sit amet dignissim est dolor in mi. Cras venenatis sodales lectus quis gravida. Morbi sed ipsum sit amet diam sodales pellentesque. Aliquam pharetra enim sed elementum dapibus. Proin non dignissim diam. Donec consectetur lacinia libero, a porttitor leo mattis non. In sed dictum velit. Cras fermentum vehicula libero, viverra bibendum quam faucibus eget.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/ecoparque_cerro_del_santisimo_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/ecoparque_cerro_del_santisimo_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 547, 'Plaza Botero', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt leo ac justo congue tempor. Aenean convallis diam volutpat, varius nunc ac, tincidunt enim. Vestibulum fermentum, lacus eu condimentum vestibulum, nulla metus porta turpis, non tempus lorem neque rhoncus nisi. Ut sed massa congue, porttitor elit non, imperdiet erat. Duis tincidunt congue lorem, vitae hendrerit velit volutpat et. Praesent mollis fringilla ex, et hendrerit ipsum luctus et. Cras semper felis a velit vulputate, ut bibendum lectus pulvinar. Morbi nec nibh ut ipsum porttitor sagittis. In ut rutrum ex. Duis accumsan auctor ligula at egestas. Vivamus sit amet risus ac eros ultrices rhoncus at sed est. Suspendisse eu nisl faucibus, rhoncus neque eu, pharetra enim. Aliquam erat volutpat. Quisque tempor luctus sapien vel viverra. Nulla quis nunc at ante venenatis dignissim eget tempus metus.
Quisque aliquam urna ex, nec sagittis risus convallis id. Phasellus sit amet nisi luctus, elementum ligula vel, pulvinar tortor. Pellentesque eu purus non metus porttitor egestas. Sed feugiat, libero aliquam vehicula mattis, nisl quam placerat arcu, sit amet dignissim est dolor in mi. Cras venenatis sodales lectus quis gravida. Morbi sed ipsum sit amet diam sodales pellentesque. Aliquam pharetra enim sed elementum dapibus. Proin non dignissim diam. Donec consectetur lacinia libero, a porttitor leo mattis non. In sed dictum velit. Cras fermentum vehicula libero, viverra bibendum quam faucibus eget.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_botero_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_botero_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_botero_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 105, 'Museo La Tertulia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt leo ac justo congue tempor. Aenean convallis diam volutpat, varius nunc ac, tincidunt enim. Vestibulum fermentum, lacus eu condimentum vestibulum, nulla metus porta turpis, non tempus lorem neque rhoncus nisi. Ut sed massa congue, porttitor elit non, imperdiet erat. Duis tincidunt congue lorem, vitae hendrerit velit volutpat et. Praesent mollis fringilla ex, et hendrerit ipsum luctus et. Cras semper felis a velit vulputate, ut bibendum lectus pulvinar. Morbi nec nibh ut ipsum porttitor sagittis. In ut rutrum ex. Duis accumsan auctor ligula at egestas. Vivamus sit amet risus ac eros ultrices rhoncus at sed est. Suspendisse eu nisl faucibus, rhoncus neque eu, pharetra enim. Aliquam erat volutpat. Quisque tempor luctus sapien vel viverra. Nulla quis nunc at ante venenatis dignissim eget tempus metus.
Quisque aliquam urna ex, nec sagittis risus convallis id. Phasellus sit amet nisi luctus, elementum ligula vel, pulvinar tortor. Pellentesque eu purus non metus porttitor egestas. Sed feugiat, libero aliquam vehicula mattis, nisl quam placerat arcu, sit amet dignissim est dolor in mi. Cras venenatis sodales lectus quis gravida. Morbi sed ipsum sit amet diam sodales pellentesque. Aliquam pharetra enim sed elementum dapibus. Proin non dignissim diam. Donec consectetur lacinia libero, a porttitor leo mattis non. In sed dictum velit. Cras fermentum vehicula libero, viverra bibendum quam faucibus eget.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_la_tertulia_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_la_tertulia_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 401, 'Piedra del peñol', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque quis tortor tristique venenatis. Donec pellentesque lacus tortor. Nam volutpat elit vitae volutpat malesuada. Duis mollis risus massa, in efficitur augue tincidunt sed. In aliquam arcu erat, a varius nulla tempus nec. Ut non justo at magna euismod dignissim id et sapien. Sed in tincidunt sapien. Sed eu venenatis ligula. Curabitur molestie tellus ut libero sagittis, eu convallis risus facilisis. Sed diam est, dignissim at enim placerat, dignissim pulvinar elit. Aenean eget diam in mauris varius tincidunt.
Phasellus velit odio, ultrices iaculis posuere eget, scelerisque vitae erat. Ut sed suscipit sapien. Etiam id augue sit amet neque viverra congue. Aenean ullamcorper elementum mi, non suscipit velit rutrum eget. Suspendisse at euismod quam. Praesent nec molestie eros. Ut at accumsan libero, at volutpat metus. Sed commodo varius ultrices. Quisque vitae nisi non nunc dignissim faucibus. Proin euismod nec nisi vitae tristique. Donec sit amet bibendum est, quis molestie nunc. Donec felis arcu, ultricies non maximus ullamcorper, venenatis ac diam. Aenean vitae justo nec mi porta tempus lacinia ut ante. Phasellus ultrices elementum nisi, nec rhoncus dui aliquam elementum.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/piedra_del_penol_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/piedra_del_penol_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/piedra_del_penol_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 118, 'Parque Nacional del Chicamocha', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque quis tortor tristique venenatis. Donec pellentesque lacus tortor. Nam volutpat elit vitae volutpat malesuada. Duis mollis risus massa, in efficitur augue tincidunt sed. In aliquam arcu erat, a varius nulla tempus nec. Ut non justo at magna euismod dignissim id et sapien. Sed in tincidunt sapien. Sed eu venenatis ligula. Curabitur molestie tellus ut libero sagittis, eu convallis risus facilisis. Sed diam est, dignissim at enim placerat, dignissim pulvinar elit. Aenean eget diam in mauris varius tincidunt.
Phasellus velit odio, ultrices iaculis posuere eget, scelerisque vitae erat. Ut sed suscipit sapien. Etiam id augue sit amet neque viverra congue. Aenean ullamcorper elementum mi, non suscipit velit rutrum eget. Suspendisse at euismod quam. Praesent nec molestie eros. Ut at accumsan libero, at volutpat metus. Sed commodo varius ultrices. Quisque vitae nisi non nunc dignissim faucibus. Proin euismod nec nisi vitae tristique. Donec sit amet bibendum est, quis molestie nunc. Donec felis arcu, ultricies non maximus ullamcorper, venenatis ac diam. Aenean vitae justo nec mi porta tempus lacinia ut ante. Phasellus ultrices elementum nisi, nec rhoncus dui aliquam elementum.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_del_chicamocha_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_del_chicamocha_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_del_chicamocha_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 88, 'Bocas de Ceniza', 'Phasellus velit odio, ultrices iaculis posuere eget, scelerisque vitae erat. Ut sed suscipit sapien. Etiam id augue sit amet neque viverra congue. Aenean ullamcorper elementum mi, non suscipit velit rutrum eget. Suspendisse at euismod quam. Praesent nec molestie eros. Ut at accumsan libero, at volutpat metus. Sed commodo varius ultrices. Quisque vitae nisi non nunc dignissim faucibus. Proin euismod nec nisi vitae tristique. Donec sit amet bibendum est, quis molestie nunc. Donec felis arcu, ultricies non maximus ullamcorper, venenatis ac diam. Aenean vitae justo nec mi porta tempus lacinia ut ante. Phasellus ultrices elementum nisi, nec rhoncus dui aliquam elementum.
Phasellus finibus diam erat, ut dapibus nisl consectetur non. Quisque nisl diam, mollis id scelerisque ut, vestibulum vitae arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus gravida, sollicitudin nulla nec, fringilla urna. Proin aliquet ante et augue blandit, vel facilisis ligula sodales. Nullam vestibulum felis non nunc elementum molestie. Nulla sed sem quis urna hendrerit volutpat. Nulla a leo sit amet urna dictum venenatis suscipit vel ipsum. Vestibulum tempus feugiat iaculis. Maecenas ac congue leo.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/bocas_ceniza_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/bocas_ceniza_2.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 547, 'Parque Explora', 'Phasellus velit odio, ultrices iaculis posuere eget, scelerisque vitae erat. Ut sed suscipit sapien. Etiam id augue sit amet neque viverra congue. Aenean ullamcorper elementum mi, non suscipit velit rutrum eget. Suspendisse at euismod quam. Praesent nec molestie eros. Ut at accumsan libero, at volutpat metus. Sed commodo varius ultrices. Quisque vitae nisi non nunc dignissim faucibus. Proin euismod nec nisi vitae tristique. Donec sit amet bibendum est, quis molestie nunc. Donec felis arcu, ultricies non maximus ullamcorper, venenatis ac diam. Aenean vitae justo nec mi porta tempus lacinia ut ante. Phasellus ultrices elementum nisi, nec rhoncus dui aliquam elementum.
Phasellus finibus diam erat, ut dapibus nisl consectetur non. Quisque nisl diam, mollis id scelerisque ut, vestibulum vitae arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis purus gravida, sollicitudin nulla nec, fringilla urna. Proin aliquet ante et augue blandit, vel facilisis ligula sodales. Nullam vestibulum felis non nunc elementum molestie. Nulla sed sem quis urna hendrerit volutpat. Nulla a leo sit amet urna dictum venenatis suscipit vel ipsum. Vestibulum tempus feugiat iaculis. Maecenas ac congue leo.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_explora_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_explora_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_explora_1.jpg');
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 401, 'Plazoleta de los Zócalos', 'Quisque aliquam urna ex, nec sagittis risus convallis id. Phasellus sit amet nisi luctus, elementum ligula vel, pulvinar tortor. Pellentesque eu purus non metus porttitor egestas. Sed feugiat, libero aliquam vehicula mattis, nisl quam placerat arcu, sit amet dignissim est dolor in mi. Cras venenatis sodales lectus quis gravida. Morbi sed ipsum sit amet diam sodales pellentesque. Aliquam pharetra enim sed elementum dapibus. Proin non dignissim diam. Donec consectetur lacinia libero, a porttitor leo mattis non. In sed dictum velit. Cras fermentum vehicula libero, viverra bibendum quam faucibus eget.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta neque quis tortor tristique venenatis. Donec pellentesque lacus tortor. Nam volutpat elit vitae volutpat malesuada. Duis mollis risus massa, in efficitur augue tincidunt sed. In aliquam arcu erat, a varius nulla tempus nec. Ut non justo at magna euismod dignissim id et sapien. Sed in tincidunt sapien. Sed eu venenatis ligula. Curabitur molestie tellus ut libero sagittis, eu convallis risus facilisis. Sed diam est, dignissim at enim placerat, dignissim pulvinar elit. Aenean eget diam in mauris varius tincidunt.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plazoleta_de_los_zocalos_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plazoleta_de_los_zocalos_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plazoleta_de_los_zocalos_1.jpg');


-- ----------------------------
-- Records of hotels
-- ----------------------------
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Toscana Plaza', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/toscana_plaza_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/toscana_plaza_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/toscana_plaza_1.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'bootiquelimonar', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/bootiquelimonar_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/bootiquelimonar_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/bootiquelimonar_1.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Central House', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/central_house_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/central_house_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/central_house_2.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Casa Santafe', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_santafe_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_santafe_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_santafe_3.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Tap Tap Hotel', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/tap_tap_hotel_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/tap_tap_hotel_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/tap_tap_hotel_2.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Nirvana', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/nirvana_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/nirvana_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/nirvana_3.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Santelmo Cali', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/santelmo_cali_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/santelmo_cali_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/santelmo_cali_3.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Embajada Real', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/embajada_real_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/embajada_real_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/embajada_real_3.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Ayenda 1069 Alfay', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ayenda_1069_alfay_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ayenda_1069_alfay_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ayenda_1069_alfay_2.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Casa Vallecaucana', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_vallecaucana_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_vallecaucana_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_vallecaucana_3.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Medellín 33', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/medellin_33_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/medellin_33_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/medellin_33_1.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'North House', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/north_house_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/north_house_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/north_house_1.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Ofix', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ofix_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ofix_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ofix_1.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Selina', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/selina_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/selina_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/selina_1.jpg');
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Stein Colonial', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/stein_colonial_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/stein_colonial_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/stein_colonial_1.jpg');

-- ----------------------------
-- Records of restaurants
-- ----------------------------
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 118, 'Batuto', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/battuto_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/battuto_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/battuto_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 150, 'Cantina la 15', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cantina_la_15_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cantina_la_15_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cantina_la_15_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 401, 'Casa cuba', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/casa_cuba_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/casa_cuba_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/casa_cuba_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 118, 'Cure Cuisine', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cure_cuisine_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cure_cuisine_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cure_cuisine_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 547, 'Della Nonna Trattoria', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/della_nonna_trattoria_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/della_nonna_trattoria_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/della_nonna_trattoria_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 547, 'La Chagra', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_chagra_2.JPG,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_chagra_3.JPG}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_chagra_1.JPG');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 150, 'La Comitiva', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_comitiva_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_comitiva_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_comitiva_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 107, 'Matiz', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/matiz_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/matiz_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/matiz_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 88, 'Miura Steak House', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/miura_steak_house_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/miura_steak_house_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/miura_steak_house_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 150, 'Platillos Voladores', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/platillos_voladores_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/platillos_voladores_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/platillos_voladores_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 107, 'Quinua Y Amaranto', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/quinua_y_amaranto_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/quinua_y_amaranto_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/quinua_y_amaranto_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 88, 'Rodizio carne e Vinho ', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/rodizio_carne_e_vinho_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/rodizio_carne_e_vinho_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/rodizio_carne_e_vinho_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 401, 'Vecchio Forno G', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/vecchio_forno_g_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/vecchio_forno_g_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/vecchio_forno_g_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 118, 'Zekkei', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/zekkei_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/zekkei_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/zekkei_1.jpg');
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 401, 'El Bacchanal', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/el_bacchanal_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/el_bacchanal_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/el_bacchanal_3.jpg');

-- ----------------------------
-- Records of review_touristic_places
-- ----------------------------
INSERT INTO "public"."review_touristic_places" VALUES (DEFAULT, 1, 11, 'Melo', 'Esta Melisisisimo', 0);
INSERT INTO "public"."review_touristic_places" VALUES (DEFAULT, 1, 11, 'Good', 'Buen lugar para pasar el rato', 0);