-- ----------------------------
-- Records of touristic_places
-- ----------------------------
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 88, 'Parque Cultural del Caribe', 'Es un complejo cultural ubicado en Barranquilla, Colombia, dedicado a promover el patrimonio natural, cultural e histórico de la región Caribe colombiana. El parque está constituído por la plaza Mario Santo Domingo y el Museo del Caribe, además de ser el primer museo regional del país, es el eje central del Parque. Fue construido para albergar la memoria histórica, cultural y natural de los ocho departamentos del Caribe colombiano.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_cultural_del_caribe_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_cultural_del_caribe_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_cultural_del_caribe_1.jpg', -74.780362, 10.986314);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 118, 'San Juan de Girón', 'Más conocido como Girón, es un municipio del departamento de Santander, que forma parte del área Metropolitana de Bucaramanga al noreste de Colombia. El municipio se conoce a nivel nacional por su casco antiguo caracterizado por su arquitectura colonial española.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_juan_de_giron_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_juan_de_giron_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_juan_de_giron_1.jpg', -73.184481, 7.073640);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 88, 'Paseo Bolívar', 'Es la avenida más importante de Barranquilla, Colombia, alrededor de la cual surgió y se expandió la urbe. Está ubicado en el centro histórico de la ciudad y sobre él se encuentran la alcaldía, la iglesia de San Nicolás y numerosas edificaciones comerciales y financieras. En su remate norte se encuentra la plaza de Bolívar con la estatua ecuestre de Simón Bolívar.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/paseo_bolivar_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/paseo_bolivar_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/paseo_bolivar_1.jpg', -74.779827, 10.982942);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 118, 'Ecoparque Cerro del Santísimo', 'Es un sitio turístico ubicado en la Vereda Helechales, sector rural de Floridablanca (Santander), conocido por poseer una escultura de Jesús de Nazaret de 35 m de alto incluido su pedestal de 6 ,1​ que incluye una estructura tríptica con 2 ascensores panorámicos y una escalera para permitir el acceso al mirador principal, el cual se encuentra a una altura de 40 m de alto y desde el cual se tiene una panorámica de Floridablanca y parte de Bucaramanga. Es un sitio de peregrinaje en Semana Santa, sobre todo para realizar el Viacrucis en Viernes Santo.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/ecoparque_cerro_del_santisimo_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/ecoparque_cerro_del_santisimo_1.jpg', -73.070238, 7.082824);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 107, 'Plaza Bolivar', 'Es la plaza principal de la ciudad de Bogotá y de Colombia, la cual es un Monumento Nacional de Colombia. Está ubicada en el centro de la ciudad y a su alrededor se encuentran las principales edificaciones de la ciudad de Bogotá.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_bolivar_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_bolivar_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_bolivar_1.jpg', -74.078232, 4.598121);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 401, 'Museo Histórico Comunitario', 'Es una casa de estilo antigua, donde tiene colecciones de los objetos representativos de lo que fue y es la cultura guatapense en otras épocas, allí pueden disfrutar de la historia y la cultura de los ancestros de la comunidad.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_historico_comunitario_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_historico_comunitario_1.jpg', -75.162999, 6.233178);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 107, 'Chorro de Quevedo', 'Es un lugar público de Bogotá, aquí estableció su guarnición militar Gonzalo Jiménez de Quesada, antes de fundar la ciudad en este mismo lugar en 1538. Se encuentra enmarcada por construcciones coloniales y de principios del siglo XX.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/chorro_quevedo_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/chorro_quevedo_1.jpg', -74.072136, 4.597113);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 547, 'Plaza Botero', 'Ubicado en el centro de Medellín, es un punto de referencia e ícono de Antioquia expresión artística. Esta plaza alberga una enorme exposición de esculturas del artista Fernando Botero. Aquí, hay 23 obras monumentales que lo convierten en el más grande Exposición al aire libre de esculturas en el mundo de Botero que donó a la ciudad.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_botero_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_botero_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plaza_botero_1.jpg', -75.570830, 6.252442);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 401, 'Piedra del peñol', 'Es un monolito de 220 metros de altura, localizado en El Peñol-Guatapé, Antioquia, Colombia. La piedra de El Peñol es una masa granítica, compuesta por cuarzo, feldespato y mica. Actualmente se puede acceder a su cumbre subiendo los 715 escalones construidos en el monolito.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/piedra_del_penol_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/piedra_del_penol_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/piedra_del_penol_1.jpg', -75.195843, 6.223611);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 118, 'Parque Nacional del Chicamocha', 'Es un parque temático de reciente creación, es uno de los pocos parques naturales de Colombia dedicados al ecoturismo, siendo por tanto uno de los sitios turísticos más importantes del país. Fue abierto al público el sábado 2 de diciembre de 2006.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_del_chicamocha_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_del_chicamocha_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_del_chicamocha_1.jpg', -73.007294, 6.791810);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 150, 'Museo La Tertulia', 'Es un museo de arte, el primero de arte moderno​ y con la colección de obras en soporte de papel más importante del país, situado en la ciudad de Cali, Colombia. Cuenta con una importante colección de arte americano y colombiano, en particular de obra gráfica, exhibida en un edificio dedicado a la muestra permanente. En sus salas tiene lugar una actividad constante de exposiciones de arte moderno y contemporáneo.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_la_tertulia_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/museo_la_tertulia_1.jpg', -76.547492, 3.450281);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 88, 'Bocas de Ceniza', 'Es el punto de desembocadura del río Magdalena en el Mar Caribe. Debe su nombre al color cenizo que toman las aguas del océano al recibir las del río. En la actualidad, el río desemboca en el mar a través de un canal artificial construido en los años 1930 para que la fuerza y la velocidad de la corriente muevan los sedimentos y permitan la navegación.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/bocas_ceniza_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/1280P.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/bocas_ceniza_2.jpg', -74.868812, 11.090622);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 547, 'Parque Explora', 'Es un museo interactivo para la apropiación y divulgación de la ciencia y la tecnología ubicado en la ciudad de Medellín,​ con 22 mil metros cuadrados de área interna y 15 mil de plazas públicas que alberga más de 300 experiencias interactivas, una sala infantil, auditorios, salas de exposiciones temporales y el acuario de agua dulce más grande de Latinoamérica.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_explora_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_explora_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_explora_1.jpg', -75.567749, 6.271081);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 401, 'Plazoleta de los Zócalos', 'Se encuentra ubicada en la ciudad de Guatapé, departamento de Antioquia, Colombia. La misma debe su nombre a un cacique indígena oriundo de la región. Tiene un área aproximado de casi 70 kilómetros y se levanta a orillas del embalse Peñol-Guatapé. Es una ciudad que se ha hecho importante destino turístico desde inicios del siglo XX, cuando algunos lugareños decidieron pintar sus casas con llamativos y bellos colores.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plazoleta_de_los_zocalos_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plazoleta_de_los_zocalos_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/plazoleta_de_los_zocalos_1.jpg', -75.162867, 6.233818);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 608, 'Parque Nacional Natural Utría', 'Es considerado como único en su tipo por contener gran variedad de ecosistemas, que van desde el marino hasta el selvático. Enmarcada por la inmensidad del Océano Pacífico y las estribaciones de la Serranía del Baudó, se estima como uno de los parques nacionales más biodiversos no solo dentro de Colombia sino en el mundo.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_utria_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_utria_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_nacional_utria_1.jpg', -77.236192, 6.020823);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 150, 'Cristo Rey', 'Es una estatua de 26 metros de altura ubicada en el Cerro los Cristales a 1440 msnm en el corregimiento Los Andes, al occidente de la ciudad de Santiago de Cali, Colombia. El cerro recibe ese nombre debido a la gran cantidad de cuarzos que podían recogerse en sus alrededores.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cristo_rey_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cristo_rey_4.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cristo_rey_1.jpg', -76.567054, 3.435927);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 547, 'Parque Arvi', 'También conocido como Parque Regional Ecoturístico, es una riqueza natural de Medellín. Fue declarado reserva forestal protectora en 1970. Es un espacio público que ofrece una gran variedad de experiencias para todos los gustos. Desde allí, logras hacer tangible el límite de lo urbano y lo rural dentro de la misma ciudad.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_arvi_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_arvi_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/parque_arvi_3.jpeg', -75.519458, 6.278230);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 877, 'Ciudad Perdida', 'También conocida como Teyuna o Buritaca-200,​ fue un antiguo poblado indígena tayrona y sitio arqueológico perteneciente a la ciudad de Santa Marta, en Colombia. Fue construido alrededor del siglo VIII de nuestra era y es considerado como uno de los principales sitios arqueológicos de Colombia.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/ciudad_perdida_2.jpg,""}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/ciudad_perdida_1.jpg', -73.927322, 11.038398);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 857, 'San Rafael', 'Es un municipio de Colombia, localizado en la subregión Oriente del departamento de Antioquia. Limita por el norte con los municipios de Alejandría y San Roque, por el este y el sur con el municipio de San Carlos y por el oeste con los municipios de Guatapé y Alejandría.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_rafael_3.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_rafael_2.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/san_rafael_1.jpg', -75.037332, 6.293544);
INSERT INTO "public"."touristic_places" VALUES (DEFAULT, 469, 'Caño Cristales', 'Es un río de Colombia que está ubicado en la sierra de la Macarena, en el municipio del mismo nombre, en el departamento del Meta. Ha sido denominado «el río de los dioses», «el río de los siete colores», «el arco iris que se derritió» e, incluso, «el río más hermoso del mundo», ya que en su fondo se reproducen plantas acuáticas que con la exposición al sol cambian de color en un proceso que va desde el verde hasta un rojo intenso. Esto produce el efecto visual de estar frente a un río de seis colores: rojo, amarillo y verde, por las plantas; negro, por el agua de selva que baja por allí; azul, por el reflejo del cielo; y blanco, por la espuma formada por las caídas de agua.', '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cano_cristales_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cano_cristales_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/touristic_places/cano_cristales_2.jpg', -73.811861, 2.264267);

-- ----------------------------
-- Records of hotels
-- ----------------------------
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Toscana Plaza', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/toscana_plaza_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/toscana_plaza_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/toscana_plaza_1.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'bootiquelimonar', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/bootiquelimonar_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/bootiquelimonar_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/bootiquelimonar_1.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Central House', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/central_house_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/central_house_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/central_house_2.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Casa Santafe', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_santafe_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_santafe_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_santafe_3.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Tap Tap Hotel', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/tap_tap_hotel_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/tap_tap_hotel_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/tap_tap_hotel_2.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Nirvana', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/nirvana_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/nirvana_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/nirvana_3.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Santelmo Cali', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/santelmo_cali_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/santelmo_cali_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/santelmo_cali_3.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Embajada Real', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/embajada_real_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/embajada_real_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/embajada_real_3.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Ayenda 1069 Alfay', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ayenda_1069_alfay_1.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ayenda_1069_alfay_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ayenda_1069_alfay_2.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Casa Vallecaucana', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_vallecaucana_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_vallecaucana_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/casa_vallecaucana_3.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Medellín 33', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/medellin_33_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/medellin_33_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/medellin_33_1.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'North House', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/north_house_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/north_house_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/north_house_1.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 547, 'Ofix', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ofix_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ofix_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/ofix_1.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 107, 'Selina', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/selina_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/selina_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/selina_1.jpg', NULL, NULL);
INSERT INTO "public"."hotels" VALUES (DEFAULT, 150, 'Stein Colonial', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/stein_colonial_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/stein_colonial_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/hotels/stein_colonial_1.jpg', NULL, NULL);

-- ----------------------------
-- Records of restaurants
-- ----------------------------
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 118, 'Batuto', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/battuto_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/battuto_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/battuto_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 150, 'Cantina la 15', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cantina_la_15_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cantina_la_15_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cantina_la_15_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 401, 'Casa cuba', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/casa_cuba_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/casa_cuba_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/casa_cuba_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 118, 'Cure Cuisine', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cure_cuisine_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cure_cuisine_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/cure_cuisine_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 547, 'Della Nonna Trattoria', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/della_nonna_trattoria_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/della_nonna_trattoria_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/della_nonna_trattoria_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 547, 'La Chagra', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_chagra_2.JPG,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_chagra_3.JPG}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_chagra_1.JPG', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 150, 'La Comitiva', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_comitiva_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_comitiva_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/la_comitiva_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 107, 'Matiz', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/matiz_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/matiz_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/matiz_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 88, 'Miura Steak House', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/miura_steak_house_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/miura_steak_house_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/miura_steak_house_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 150, 'Platillos Voladores', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/platillos_voladores_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/platillos_voladores_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/platillos_voladores_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 107, 'Quinua Y Amaranto', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/quinua_y_amaranto_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/quinua_y_amaranto_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/quinua_y_amaranto_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 88, 'Rodizio carne e Vinho ', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/rodizio_carne_e_vinho_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/rodizio_carne_e_vinho_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/rodizio_carne_e_vinho_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 401, 'Vecchio Forno G', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/vecchio_forno_g_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/vecchio_forno_g_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/vecchio_forno_g_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 118, 'Zekkei', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/zekkei_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/zekkei_3.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/zekkei_1.jpg', NULL, NULL);
INSERT INTO "public"."restaurants" VALUES (DEFAULT, 401, 'El Bacchanal', NULL, '{https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/el_bacchanal_2.jpg,https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/el_bacchanal_1.jpg}', 'https://juanjogv-development-bucket.s3.us-east-2.amazonaws.com/ecotrips/restaurants/el_bacchanal_3.jpg', NULL, NULL);

-- ----------------------------
-- Records of review_touristic_places
-- ----------------------------
INSERT INTO "public"."review_touristic_places" VALUES (DEFAULT, 1, 11, 'Melo', 'Esta Melisisisimo', 0);
INSERT INTO "public"."review_touristic_places" VALUES (DEFAULT, 1, 11, 'Good', 'Buen lugar para pasar el rato', 0);